export const CAROUSEL_ITEMS: Array<{
  imageUrl: string;
  alt: string;
  blurDataURL: string;
}> = [
  {
    imageUrl: "/kota-kinabalu/kota1.png",
    alt: "kota1",
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVR4nAHZACb/AIuMlKSlqrS4urO5vaCiqo+Nl4aGk3yAk2pzi1ZjewC+tZ/It6P/4r3/4r3ns6DCmZC5m5SLiZBveollcoIA2sCW/+2T//KD/9dZ/6dI/51F+KZ6v6iOtKeQpqCQAIt/bc6aV+mjRu2WOe55LctlKZRhRYBtZG9pZWViXgByb2ljYFx/cmajgW2WaVZfTz45NzxfXmBFS1I7QkwALiknHRgVPDAjdlpGaEo2JBoXMCosQUFCJSkvIScvABsQCBoMBhsOBioZDysYDhkAACMVDTcrJisqKB8gIX8ZXLJQDQRaAAAAAElFTkSuQmCC",
  },
  {
    imageUrl: "/japan/japan1.png",
    alt: "japan1",
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVR4nAHZACb/AGdvW3B0ZjxAKk5SPTxBKkBBKoGDbFlaRj0+J0FCKwBOVz62vLGgopqztKyUlYZrblxXWkRTVTw6OyQ6PB0AVlMq2NG+7/P29PX1////5ubjiIJzRkMkRDoRQDYJADUuFmNYNt7d1Pz7+/P28/H09LqnoVIiDlspFYclDwAFCAAHAwA8NzG1uby5rqbHwr3Z0s14NSp8MiGINiIAOTQkSC0cQCMVRjQnTzEic1NMvLa9hVZSXSEWYycYAD8wJFkzGm5CJZlhQnNJOFlHSJ2zwKmbo5VcTZdKMYpGWFi0XfJ8AAAAAElFTkSuQmCC",
  },
  {
    imageUrl: "/japan/japan2.png",
    alt: "japan2",
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVR4nAHZACb/ANH+/6PY/zqJ+keZ/0OU/zuJ/TuJ+zuJ+zeE+zyI/wB8yP+Ay/9dsP9arf9TpP9frf9Glf9Dkf9Kmf9Nm/8AUHCEVpffdsf/d83/csv/cM3/m+j/tPL/a8X/cM3/ACgyACw5D0pWMldmQl94bGubr6rAu6GtlmGOjk9/gwBCShomNQgiLwEVGQAAAAA2PAAsNAASEwBBTAAtPAAAKSgCDg4AIyMCAAQAJCUXNz4UJS0ADhAAOD4OMDsQAJGVcIKGZ3qCX3R9X2dwUXl+XXl+X2FmRoeLZKeog/9CXfBDQAHOAAAAAElFTkSuQmCC",
  },
  {
    imageUrl: "/paris/paris1.png",
    alt: "paris1",
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAKCAIAAAD3rtNaAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5UlEQVR4nGPg42Xl4mJlYmbm4mIV5GeXkxRUVxBhEOTnYOdgY2VjExBgV5IVlJXklxDlYZCTEhAS5OXl5ZWQEFZRFDbSlNBUEmVQkhVWlhUx1FNtrk4VFuLSUhFTUxJlUJQVkhDnd3Y0fXlvKy8fh7ycsDjEBCU5UWsL3VfXlkhICMlICcrJCDHoa8lISYlnJvr8/7bHzFRHRkpQT0OSQVVZXExc/OzW7q9Xl8zuKVZRU+EX4GYIC/FOSIhZvqBv2eIp545sKi4u8PJyY1i5fNOzz/+v3n0wa/q8mTOnFpfm1jU3AQBAFjYLRwfe4QAAAABJRU5ErkJggg==",
  },
  {
    imageUrl: "/hongkong/hongkong1.png",
    alt: "hongkong1",
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAIAAAC+zks0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVR4nAHZACb/AEBDQj9BQT4+Pjw8PDo8OzM0NDM0My8xMSoqKSUlIwBzcnB2c3Jubm1qbGtgYGBbW1pZWVZZWVVRUUtBQTsAta6jycK20cq/u7KooJuWjoiEpZuUua2jiIZ5ZmZbAOLazZ+Wif/16//47tLMxKGem6WYi7qnmIV/b15bSwBbVUxCPjN/eXOpopSKhHZ3b11WTz1DQC0NDgoCAgAANDEnQD0yV048RDstOzcqalxAQTsrFRYTAQIBBAQCABcWEi8pH3VoUWpcRUI7LUg+KzUtHwAAAAQEAgICAQMvTFY/CppkAAAAAElFTkSuQmCC",
  },
  {
    imageUrl: "/london/london1.png",
    alt: "london1",
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAGCAIAAAB1kpiRAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAxUlEQVR4nAG6AEX/AG1NQkc0KAAAAFpVVsLEyP///9fW2FNQWUU2PUpFSgB6Y0NmSD1RODI0KCecn5/29/ePh4g1KS0xJCc0LzAAQmkAWGQYcmk4U0wtOzs0ZWJhX11gJSYvFh0qHR4kAFI6KVZAKWlIMl5KO19aUmxlVkFISyQsMExTVSQoLQB1RTF8RDKEXk+nn5R9e3VYVEtDRUIABQUlKSc2OzoAfkYvgFZAqaOTp6aaW1pXWVhXVlVQERUUEBMTFxkZ/CU6xz48IRoAAAAASUVORK5CYII=",
  },
  {
    imageUrl: "/london/london2.png",
    alt: "london2",
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAGCAIAAAB1kpiRAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAxUlEQVR4nAG6AEX/AJyciUBFSCAoKS1APa26vPv7/6qstcSypKCZkeni1gBOVUWMjYuFj3oPHBiMm5erqbaOf3++rqSfmZP79ekAXFxahYZ/vMSWMzstYWpnn4+RoImE3tHCtayi//rtAHN5hl1dYputvlJTVYB/iGVdXnJjRXZpXYZ6dKqaiwCQla1PTlWBh5Odm6WEhJhcXGhaV00RDg8fHiKEfXgAY2NtGhcaSURGpaSwiomYZWVyT05TTEhIBAACTkdDb6ZWpfg0iIkAAAAASUVORK5CYII=",
  },
  {
    imageUrl: "/london/london3.png",
    alt: "london3",
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAKCAIAAAD3rtNaAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA50lEQVR4nAHcACP/ABgSEqeGO/nSbv/qhP/nh//hgv3UcwAhGhfau2z/7pvv0Y7qzo3bwITpyoEAJB4a5sh91Ll5sp5qwa15xq98uqBuACgkHtvAddS5cv/3pv/6q//knfDPiwAkHhrOrm3VuXj/4ab/5rvy1pHRsnAAQjImrYZkn4JT//3Z3NTLwKBfxKJfAJRZOduZYoNZNmdgTfDWoubFhtq1cwC0ZzfylE2gYTIqJiL02qn+5rfnx5EAPVI2TmlHUE8po4tU8M+Mqo9lIhoWAFxVJW9uNYl4L6uIM35jNDAlGgMBBRiideouRQNBAAAAAElFTkSuQmCC",
  },
  {
    imageUrl: "/london/london4.png",
    alt: "london4",
    blurDataURL:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAKCAIAAAD3rtNaAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA50lEQVR4nAHcACP/AEdfOmaISpezab3Ur4ymhpKzdJm5ZQBNYkCduIyKo3O/2paduW5ylEyFp1wAPVIogZ9bZYJAgKFNaIBNKDwuX3dPAF9wRa7FhWl6UISWZniMb2N2Wai2lwBvdF6fsHwdIyBFUzjs/6nN6ZLD24oAp56ifnhuAAURCBEYSEQ7NTQrLC0kAF9aXGRfYR8jKCYqMUxIQykpIyUjHQBAPj5fXl5BQkg5PEJRTlFVUlNGQj8ASkZGRkNDKikqMTAxPTw8SkhIU1BRADg3NyAgIB0dHTo4OUZDRERCQkdFRRUoTaimAxgZAAAAAElFTkSuQmCC",
  },
];
